# Site settings
# These are used to personalize your new site.
# You can access them in HTML files via {{ site.title }}, {{ site.email }}, etc.
# Create custom variables like {{ site.myvariable }}.

title: Meaning Blog
email: skylerboyer@gmail.com
description: >-
  This is a blog about meaning and everything else.
url: "https://lineardigressions.github.io/" # the subpath of your site, e.g. /blog
baseurl: "/meaningBlog" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: customtheme
plugins:
  - jekyll-feed

# Order of header pages in navigation
header_pages:
- index.md
- _pages/about.md

include:
  - _pages

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - build_and_copy_site.sh
  - customtheme